services:
  database:
    image: postgres:16.0-alpine3.18
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  database-test:
    image: postgres:16.0-alpine3.18
    env_file:
      - .env.test
    ports:
      - 5433:5432

volumes:
  pgdata:
